version: '3.7'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: my-dynamodb
    hostname: dynamodb
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SERVICE_NAME=my-dynamodb
      - SERVICE_TAGS=dev
      - SERVICE_PORT_NUMBER=8000
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy